### ISSUE TITLE
Can't run parse-server

### ISSUE THREAD

**Issue by vstepanyuk** [yongjhih/docker-parse-server#20]
parse-server_1     | [nodemon] starting `node index.js`
parse-server_1     | /parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:58
parse-server_1     |         throw new Error(this.constructor.name + " requires an adapter");

**Comment by notentered** [comment]
Same problem :)

```
parse-server_1      | [nodemon] 1.9.1
parse-server_1      | [nodemon] to restart at any time, enter `rs`
parse-server_1      | [nodemon] watching: /parse/cloud/**/*
parse-server_1      | [nodemon] starting `node index.js`
parse-server_1      | /parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:51
parse-server_1      |         throw new Error(this.constructor.name + " requires an adapter");
parse-server_1      |         ^
parse-server_1      | 
parse-server_1      | Error: UserController requires an adapter
parse-server_1      |     at UserController.validateAdapter (/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:51:15)
parse-server_1      |     at UserController.validateAdapter (/parse/node_modules/parse-server/lib/Controllers/UserController.js:60:86)
parse-server_1      |     at UserController.set (/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:80:12)
parse-server_1      |     at UserController.AdaptableController (/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:39:18)
parse-server_1      |     at new UserController (/parse/node_modules/parse-server/lib/Controllers/UserController.js:50:83)
parse-server_1      |     at new ParseServer (/parse/node_modules/parse-server/lib/ParseServer.js:232:26)
parse-server_1      |     at new _ParseServer (/parse/node_modules/parse-server/lib/index.js:34:16)
parse-server_1      |     at Object.<anonymous> (/parse/index.js:88:11)
parse-server_1      |     at Module._compile (module.js:413:34)
parse-server_1      |     at Object.Module._extensions..js (module.js:422:10)
parse-server_1      | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by yongjhih** [comment]
Try to update image by the following command:

```
docker pull yongjhih/parse-server
```

**Comment by notentered** [comment]
Still the same. It might be me, actually. This is my very first experience with parse at all.

Also, if I comment this line in the compose yml:
```
VERIFY_USER_EMAILS: $VERIFY_USER_EMAILS # false
```
the problem disappear... at least on startup :)

**Comment by yongjhih** [comment]
I could not reproduce this issue.

https://youtu.be/ZpdN0tij2FM

**Comment by notentered** [comment]
Yes, this is working.
... It really might be me :) The problem appears when VERIFY_USER_EMAILS is set to anything.

For example this is working fine:
```
APP_ID=myAppId MASTER_KEY=myMasterKey VERIFY_USER_EMAILS= docker-compose up
```

But this is not:
```
APP_ID=myAppId MASTER_KEY=myMasterKey VERIFY_USER_EMAILS=false docker-compose up
```

**Comment by yongjhih** [comment]
Use `VERIFY_USER_EMAILS=0` or `VERIFY_USER_EMAILS=1` instead

**Comment by yongjhih** [comment]
ref. #34
