### ISSUE TITLE
Prase dashboard missing missing app setting page?

### ISSUE THREAD

**Issue by katopz** [yongjhih/docker-parse-server#34]
Is this only me?
![screen shot 2559-04-28 at 21 23 57](https://cloud.githubusercontent.com/assets/97060/14889196/f28ab83e-0d87-11e6-9c70-aadcd27097a5.png)
I expected (capture from parse site)
![screen shot 2559-04-28 at 21 27 19](https://cloud.githubusercontent.com/assets/97060/14889230/2508ff3c-0d88-11e6-85f8-29dc211e7510.png)

May be I miss some config? Any hint is welcome. Thanks

**Comment by yongjhih** [comment]
No, The official screencast is the same with you:
https://youtu.be/o522ovITvW4

**Comment by katopz** [comment]
Refer to https://github.com/ParsePlatform/parse-dashboard/issues/246
It seem like I've to enable `VERIFY_USER_EMAILS` but I got
```
/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:51
        throw new Error(this.constructor.name + " requires an adapter");
        ^
Error: UserController requires an adapter
    at UserController.validateAdapter (/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:51:15)
    at UserController.validateAdapter (/parse/node_modules/parse-server/lib/Controllers/UserController.js:60:86)
    at UserController.set (/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:80:12)
    at UserController.AdaptableController (/parse/node_modules/parse-server/lib/Controllers/AdaptableController.js:39:18)
    at new UserController (/parse/node_modules/parse-server/lib/Controllers/UserController.js:50:83)
    at new ParseServer (/parse/node_modules/parse-server/lib/ParseServer.js:232:26)
    at new _ParseServer (/parse/node_modules/parse-server/lib/index.js:34:16)
    at Object.<anonymous> (/parse/index.js:88:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```
Seem like I need mail adapter there. This setup flow is super weird tho.
BTW, how can I add [adapter file](http://stackoverflow.com/questions/35777534/enabling-email-verification-for-parse-server-hosted-on-heroku) in docker parse-server? scp? rsync? git push?

Thanks

**Comment by yongjhih** [comment]
Oh, you want to enable User class, I'm taking look it

**Comment by yongjhih** [comment]
You can configure `emailAdapter` with environment variables:

```
EMAIL_MODULE=parse-server-simple-mailgun-adapter
EMAIL_FROM=xxx@mg.xxx.com
EMAIL_DOMAIN=mg.xxx.com
EMAIL_API_KEY=key-xxx
```

I'm not sure that email configuration will enable App Setttings and Analytics menu items or not.
